version: "3.3"
services:
  postgresql:
    image: postgres:12.1
    volumes:
      - "db:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pingpong_development
      POSTGRES_HOST_AUTH_METHOD: trust
  rails:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    environment:
        TZ: Europe/Moscow
        FT_ID: 86da4d34dc9a120ce5715b91fb923a56b8226e1ed1fc5297e4404875693f2890
        FT_SECRET: a8a89c12f24bfa80276e6ece6b697a18ff519916d48437ebd62956c4ea7a226e
    depends_on:
      - postgresql
  redis:
    image: redis:6.0.12-alpine
    ports:
      - "6379:6379"

volumes:
  db:
